<!-- Chatbot Wrapper -->
<div class="chatbot-wrapper">
    <!-- Floating Button -->
    <button id="ChatbotBtn" class="btn btn-primary rounded-circle shadow-lg position-fixed"
        style="bottom: 20px; right: 20px; width: 60px; height: 60px; z-index: 1050;">
        <i class="bi bi-chat-dots-fill fs-3"></i>
    </button>

    <!-- Chatbot Container -->
    <div id="ChatbotContainer" class="card shadow-lg position-fixed hidden"
        style="bottom: 90px; right: 20px; width: 320px; height: 500px; z-index: 1050;">

        <!-- Header -->
        <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
            <span>Dicimulation Staycation</span>
            <button id="CloseChatBot" class="btn btn-sm btn-light">&times;</button>
        </div>

        <!-- Messages -->
        <div id="messages" class="card-body overflow-auto" style="height: 280px; background: #f8f9fa;">
            <!-- Messages will appear here -->
        </div>

        <!-- FAQ Buttons -->
        <div id="faqButtons" class="d-flex flex-wrap justify-content-start px-2 pb-2" style="gap: 6px;">
            <!-- Buttons generated by JS -->
        </div>

        <!-- Input -->
        <div class="card-footer bg-white d-flex">
            <input type="text" id="userMessage" class="form-control me-2" placeholder="Type a message...">
            <button id="sendBtn" class="btn btn-primary">
                <i class="bi bi-send-fill"></i>
            </button>
        </div>
    </div>
</div>

<!-- Bootstrap Icons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

<script>
document.addEventListener("DOMContentLoaded", () => {
    const chatbotBtn = document.getElementById("ChatbotBtn");
    const chatbotContainer = document.getElementById("ChatbotContainer");
    const closeBtn = document.getElementById("CloseChatBot");
    const sendBtn = document.getElementById("sendBtn");
    const input = document.getElementById("userMessage");
    const messages = document.getElementById("messages");
    const faqButtons = document.getElementById("faqButtons");

    // FAQ database
    const faq = [
        { keywords: ["checkin", "check-in", "arrival", "check in"], reply: "Check-in time is 2:00 PM." },
        { keywords: ["checkout", "check-out", "departure"], reply: "Check-out time is 12:00 PM." },
        { keywords: ["pool", "swimming", "pool access"], reply: "The pool is shared among every three units, and guests can enjoy it during their stay." },
        { keywords: ["payment", "gcash", "bank transfer", "pay"], reply: "We accept GCash and bank transfer. A 50% down payment is required to secure your booking." },
        { keywords: ["location", "where", "address"], reply: "We are located at Falcons Court, Village East Avenue, Angono, 1930 Rizal, Philippines." },
        { keywords: ["amenities", "facility", "services"], reply: "We offer Free WiFi, Swimming Pool, Kitchen, BBQ Area, Parking, Netflix, and Pet-Friendly accommodations." },
        { keywords: ["booking", "reserve", "reservation"], reply: "You can book directly through our website by selecting your preferred room and dates." },
        { keywords: ["owner", "edgar", "host"], reply: "Our host, Mr. Edgar Fuentes Dicimulacion, is a Computer Engineer with 7 years of hosting experience and a 4.78-star guest rating." },
    ];

    // Show/Hide chatbot
    chatbotBtn.addEventListener("click", () => chatbotContainer.classList.toggle("hidden"));
    closeBtn.addEventListener("click", () => chatbotContainer.classList.add("hidden"));

    // Append message to chat window
    function appendMessage(text, sender) {
        const div = document.createElement("div");
        div.classList.add("mb-2", "p-2", "rounded");
        if (sender === "user") {
            div.classList.add("bg-primary", "text-white", "ms-auto");
            div.style.maxWidth = "80%";
        } else {
            div.classList.add("bg-light", "text-dark", "me-auto");
            div.style.maxWidth = "80%";
        }
        div.textContent = text;
        messages.appendChild(div);
        messages.scrollTop = messages.scrollHeight;
    }

    // Check FAQ for a reply
    function checkFAQ(userMessage) {
        userMessage = userMessage.toLowerCase();
        for (let item of faq) {
            for (let keyword of item.keywords) {
                if (userMessage.includes(keyword)) {
                    return item.reply;
                }
            }
        }
        return null;
    }

    // Send message (manual or from FAQ click)
    function sendMessage(rawMessage) {
        const message = rawMessage || input.value.trim();
        if (!message) return;

        appendMessage(message, "user");
        input.value = "";

        const faqReply = checkFAQ(message);
        if (faqReply) {
            const typingDiv = document.createElement("div");
            typingDiv.classList.add("bg-light", "p-2", "rounded", "me-auto");
            typingDiv.textContent = "Typing...";
            messages.appendChild(typingDiv);
            messages.scrollTop = messages.scrollHeight;
            setTimeout(() => {
                typingDiv.remove();
                appendMessage(faqReply, "bot");
            }, 700);
        } else {
            appendMessage("I can answer questions about our staycation. Please ask me anything!", "bot");
        }
    }

    sendBtn.addEventListener("click", () => sendMessage());
    input.addEventListener("keypress", e => { if (e.key === "Enter") sendMessage(); });

    // Create clickable FAQ buttons
    const sampleFAQ = [
        "What time is check-in?",
        "What time is check-out?",
        "Do you have a swimming pool?",
        "What are your payment options?",
        "Where is your location?"
    ];

    sampleFAQ.forEach(q => {
        const btn = document.createElement("button");
        btn.classList.add("btn", "btn-outline-primary", "btn-sm");
        btn.textContent = q;
        btn.style.fontSize = "0.85rem";
        btn.addEventListener("click", () => sendMessage(q));
        faqButtons.appendChild(btn);
    });
});
</script>

<style>
/* Hide chatbot initially */
.hidden {
    display: none;
}

/* FAQ Buttons Styling */
#faqButtons button {
    border-radius: 20px;
    white-space: nowrap;
}
</style>
