<!-- Messenger-Style Chatbot -->
<div class="chatbot-wrapper">
  <!-- Floating Button -->
  <button id="ChatbotBtn"
    class="btn btn-primary rounded-circle shadow-lg position-fixed flex justify-center items-center"
    style="bottom: 20px; right: 20px; width: 60px; height: 60px; z-index: 1050;">
    <i class="bi bi-messenger fs-3 text-white"></i>
  </button>

  <!-- Chatbot Window -->
  <div id="ChatbotContainer"
    class="card position-fixed shadow-lg hidden"
    style="bottom: 90px; right: 20px; width: 360px; height: 520px; border-radius: 20px; overflow: hidden; z-index: 1050;">

    <!-- Header (No Logo) -->
    <div class="bg-primary text-white px-3 py-2 d-flex align-items-center justify-content-between">
      <div>
        <h6 class="mb-0 fw-bold">Dicimulation Staycation</h6>
        <small>Online</small>
      </div>
      <button id="CloseChatBot" class="btn btn-light btn-sm rounded-circle">
        <i class="bi bi-x-lg"></i>
      </button>
    </div>

    <!-- Messages Area -->
    <div id="messages" class="p-3 overflow-auto" style="height: 340px; background-color: #f0f2f5;">
      <div class="text-center text-muted small mt-2">Start a conversation</div>
    </div>

    <!-- Quick FAQ Buttons -->
    <div id="faqButtons" class="px-3 py-2 d-flex flex-wrap gap-2 border-top bg-white">
      <!-- Auto-generated by JS -->
    </div>

    <!-- Input -->
    <div class="bg-white border-top px-2 py-2 d-flex align-items-center">
      <input type="text" id="userMessage" class="form-control rounded-pill me-2" placeholder="Aa">
      <button id="sendBtn" class="btn btn-primary rounded-pill px-3">
        <i class="bi bi-send-fill"></i>
      </button>
    </div>
  </div>
</div>

<!-- Bootstrap Icons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

<!-- Script -->
<script>
document.addEventListener("DOMContentLoaded", () => {
  const chatbotBtn = document.getElementById("ChatbotBtn");
  const chatbotContainer = document.getElementById("ChatbotContainer");
  const closeBtn = document.getElementById("CloseChatBot");
  const sendBtn = document.getElementById("sendBtn");
  const input = document.getElementById("userMessage");
  const messages = document.getElementById("messages");
  const faqButtons = document.getElementById("faqButtons");

  // FAQ responses
  const faq = [
    { keywords: ["checkin", "arrival"], reply: "Check-in time is 2:00 PM." },
    { keywords: ["checkout", "departure"], reply: "Check-out time is 12:00 PM." },
    { keywords: ["pool", "swimming"], reply: "Our pool is shared among every three units and open daily." },
    { keywords: ["payment", "gcash"], reply: "We accept GCash or bank transfer. 50% downpayment secures your booking." },
    { keywords: ["location", "address","located"], reply: "We are at Falcons Court, Village East Avenue, Angono, Rizal." },
    { keywords: ["amenities"], reply: "We offer WiFi, Kitchen, BBQ, Parking, Netflix, Pool, and Pet-Friendly rooms." },
    { keywords: ["booking", "reserve"], reply: "You can book directly on our website via the Booking page." }
  ];

  // Show/Hide chatbot
  chatbotBtn.addEventListener("click", () => chatbotContainer.classList.toggle("hidden"));
  closeBtn.addEventListener("click", () => chatbotContainer.classList.add("hidden"));

  // Append messages
  function appendMessage(text, sender) {
    const msgDiv = document.createElement("div");
    msgDiv.classList.add("d-flex", "mb-2");

    const bubble = document.createElement("div");
    bubble.textContent = text;
    bubble.classList.add("p-2", "rounded-3", "shadow-sm");

    if (sender === "user") {
      msgDiv.classList.add("justify-content-end");
      bubble.classList.add("bg-primary", "text-white");
      bubble.style.maxWidth = "80%";
      bubble.style.borderBottomRightRadius = "4px";
    } else {
      msgDiv.classList.add("justify-content-start");
      bubble.classList.add("bg-white", "text-dark");
      bubble.style.maxWidth = "80%";
      bubble.style.borderBottomLeftRadius = "4px";
    }

    msgDiv.appendChild(bubble);
    messages.appendChild(msgDiv);
    messages.scrollTop = messages.scrollHeight;
  }

  // Check FAQ
  function checkFAQ(message) {
    message = message.toLowerCase();
    for (let item of faq) {
      for (let keyword of item.keywords) {
        if (message.includes(keyword)) return item.reply;
      }
    }
    return null;
  }

  // Send message
  function sendMessage(text) {
    const msg = text || input.value.trim();
    if (!msg) return;

    appendMessage(msg, "user");
    input.value = "";

    const reply = checkFAQ(msg);
    const typing = document.createElement("div");
    typing.classList.add("text-muted", "small", "fst-italic", "ms-2");
    typing.textContent = "Dicimulation is typing...";
    messages.appendChild(typing);
    messages.scrollTop = messages.scrollHeight;

    setTimeout(() => {
      typing.remove();
      appendMessage(reply || "Sorry, I can only answer staycation-related questions 😊", "bot");
    }, 700);
  }

  sendBtn.addEventListener("click", () => sendMessage());
  input.addEventListener("keypress", e => e.key === "Enter" && sendMessage());

  // FAQ Quick Buttons
  const quick = [
    "What time is check-in?",
    "Do you have a pool?",
    "What are your payment options?",
    "Where are you located?"
  ];
  quick.forEach(q => {
    const b = document.createElement("button");
    b.classList.add("btn", "btn-outline-primary", "btn-sm", "rounded-pill");
    b.textContent = q;
    b.addEventListener("click", () => sendMessage(q));
    faqButtons.appendChild(b);
  });
});
</script>

<!-- Style -->
<style>
.hidden { display: none; }

/* Scrollbar */
#messages::-webkit-scrollbar {
  width: 6px;
}
#messages::-webkit-scrollbar-thumb {
  background-color: rgba(0,0,0,0.2);
  border-radius: 4px;
}
</style>
