"use client";

import React, { useState, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { authService } from "@/lib/services/authService";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { KeyRound } from "lucide-react";

function TwoFactorForm() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const tempToken = searchParams?.get("temp_token") || "";

  const [code, setCode] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length < 6) {
      setError("Please enter the 6-digit verification code.");
      return;
    }
    setIsLoading(true);
    setError("");

    try {
      const verifiedUser = await authService.verifyTwoFactor({ code });

      if (verifiedUser.role === "admin") {
        router.push("/admin/dashboard");
      } else if (verifiedUser.role === "staff") {
        router.push("/staff/dashboard");
      } else {
        router.push("/");
      }
    } catch (err: any) {
      setError(err?.message || "Invalid two-factor authentication code.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="w-full max-w-md">
      <div className="text-center mb-8">
        <div className="inline-flex h-12 w-12 rounded-2xl bg-primary text-primary-foreground items-center justify-center shadow-md mb-3">
          <KeyRound className="h-6 w-6 text-gold-300" />
        </div>
        <h2 className="font-serif text-2xl font-bold text-foreground">Two-Factor Authentication</h2>
        <p className="text-xs text-muted-foreground mt-1">
          Enter the 6-digit authentication code generated by your authenticator app.
        </p>
      </div>

      <div className="rounded-2xl border border-border/80 bg-card p-6 sm:p-8 shadow-card">
        {error && (
          <div className="p-3 mb-5 rounded-xl bg-destructive/10 border border-destructive/30 text-destructive text-xs">
            {error}
          </div>
        )}

        <form onSubmit={handleVerify} className="space-y-4 text-xs sm:text-sm">
          <div>
            <label className="block text-xs font-semibold text-muted-foreground uppercase mb-1">
              Authentication Code
            </label>
            <Input
              type="text"
              maxLength={6}
              required
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
              placeholder="123456"
              className="text-center text-xl tracking-widest font-mono h-12"
            />
          </div>

          <Button type="submit" variant="default" size="lg" isLoading={isLoading} className="w-full font-bold mt-2">
            Verify Code & Continue
          </Button>
        </form>
      </div>
    </div>
  );
}

export default function TwoFactorChallengePage() {
  return (
    <div className="min-h-[85vh] flex items-center justify-center py-12 px-6 bg-background">
      <Suspense fallback={<div className="h-48 w-full max-w-md rounded-2xl bg-muted/60 animate-pulse" />}>
        <TwoFactorForm />
      </Suspense>
    </div>
  );
}
